mon0825 = {
    "FOOTBALL_B": [24, "MAIN FIELD 1", "XX"],
    "FLOORBALL_B": [24, "ISH", "SH"],
    "TENNIS_B": [10, "TC", "GP"],
    "TENNIS_G": [8, "TC", "GP"],
    "BADMINTON_B": [10, "MPH", "IQ"],
    "BADMINTON_G": [10, "MPH", "IQ"],
    "HANDBALL_G": [22, "BBC", "YY"],
    "GROUP_EXERCISE_G": [17, "GYM / DANCE STUDIO", "CC"],
    "VOLLEYBALL_B": [12, "2CAG", "RT"],
    "VOLLEYBALL_G": [12, "2CAG", "RT"],
    "TABLE_TENNIS_B": [12, "AMPHI", "DK"],
    "TABLE_TENNIS_G": [11, "AMPHI", "DK"],
    "FRISBEE_G": [21, "HF", "CL"],
    "PICKLE_BALL_B": [10, "PS", "JT"],
    "PICKLE_BALL_G": [14, "PS", "JT"],
    "HANDBALL_B": [18, "GC", "JL"],
    "CHOICE_COUNT": [
        "Choice 1",
        "Choice 2",
        "Choice 3",
        "Choice 4",
        "Choice 5",
        "Choice 6",
        "Choice 7",
        "Choice 8",
    ],
}

mon0920 = {
    "TENNIS_B": [10, "TC", "VC"],
    "TENNIS_G": [10, "TC", "VC"],
    "HANDBALL_B": [22, "GC", "JL"],
    "BASKETBALL_B": [24, "BBC", "BF"],
    "LACROSSE_G": [24, "HF", "SK"],
    "PICKLE_BALL_B": [11, "PS", "JT"],
    "PICKLE_BALL_G": [9, "PS", "JT"],
    "TABLE_TENNIS_B": [14, "AMPHI", "CJ"],
    "TABLE_TENNIS_G": [11, "AMPHI", "CJ"],
    "FLOORBALL_G": [24, "ISH", "MO"],
    "VOLLEYBALL_B": [14, "2CAG", "MY"],
    "VOLLEYBALL_G": [12, "2CAG", "MY"],
    "GROUP_EXERCISE_G": [17, "GYM / DANCE STUDIO", "CC"],
    "FOOTBALL_B": [26, "MAIN FIELD 2", "SY"],
    "BADMINTON_B": [10, "MPH", "IQ"],
    "BADMINTON_G": [14, "MPH", "IQ"],
    "CHOICE_COUNT": [
        "Choice 1",
        "Choice 2",
        "Choice 3",
        "Choice 4",
        "Choice 5",
        "Choice 6",
        "Choice 7",
        "Choice 8",
    ],
}

mon1015 = {
    "LACROSSE_G": [22, "HF", "SK"],
    "HANDBALL_B": [16, "GC", "BF"],
    "TENNIS_B": [10, "TC", "SH"],
    "TENNIS_G": [10, "TC", "SH"],
    "PICKLE_BALL_B": [10, "2CAG", "MY"],
    "PICKLE_BALL_G": [14, "2CAG", "MY"],
    "FLOORBALL_B": [26, "ISH", "CL"],
    "CHOICE_COUNT": ["Choice 1", "Choice 2", "Choice 3", "Choice 4"],
}

tues0825 = {
    "FLOORBALL_B": [26, "ISH", "SH"],
    "HANDBALL_B": [26, "GC", "JL"],
    "TABLE_TENNIS_B": [16, "Amphi", "CL"],
    "TABLE_TENNIS_G": [10, "Amphi", "CL"],
    "FOOTBALL_B": [26, "HF", "BF"],
    "BADMINTON_B": [10, "MPH", "CC"],
    "BADMINTON_G": [12, "MPH", "CC"],
    "GROUP_EXERCISE_G": [16, "GYM / DANCE STUDIO", "JT"],
    "HANDBALL_G": [24, "BBC", "YY"],
    "VOLLEYBALL_B": [12, "2CAG", "RT"],
    "VOLLEYBALL_G": [12, "2CAG", "RT"],
    "TENNIS_B": [10, "TC", "VC"],
    "TENNIS_G": [10, "TC", "VC"],
    "FRISBEE_G": [26, "MAIN FIELD 1", "SY"],
    "STREET_NETBALL_G": [26, "STDM D", "DK"],
    "CHOICE_COUNT": [
        "Choice 1",
        "Choice 2",
        "Choice 3",
        "Choice 4",
        "Choice 5",
        "Choice 6",
        "Choice 7",
        "Choice 8",
    ],
}

tues0920 = {
    "TENNIS_B": [8, "TC", "VC"],
    "TENNIS_G": [12, "TC", "VC"],
    "FOOTBALL_B": [26, "MAIN FIELD 1", "XX"],
    "HOCKEY_B": [24, "HF", "GP"],
    "FRISBEE_B": [24, "MAIN FIELD 2", "SY"],
    "FLOORBALL_G": [24, "ISH", "SH"],
    "STREET_NETBALL_G": [22, "STDM D", "DK"],
    "TABLE_TENNIS_B": [12, "AMPHI", "BF"],
    "TABLE_TENNIS_G": [11, "AMPHI", "BF"],
    "BADMINTON_B": [12, "MPH", "CJ"],
    "BADMINTON_G": [12, "MPH", "CJ"],
    "VOLLEYBALL_B": [12, "2CAG", "RT"],
    "VOLLEYBALL_G": [10, "2CAG", "RT"],
    "HANDBALL_G": [23, "GC", "MY"],
    "GROUP_EXERCISE_G": [17, "GYM / DANCE STUDIO", "CC"],
    "TCHOUKBALL_G": [24, "PS", "SK"],
    "BASKETBALL_G": [24, "BBC", "IQ"],
    "CHOICE_COUNT": [
        "Choice 1",
        "Choice 2",
        "Choice 3",
        "Choice 4",
        "Choice 5",
        "Choice 6",
        "Choice 7",
        "Choice 8",
        "Choice 9",
        "Choice 10",
    ],
}

tues1015 = {
    "PICKLE_BALL_B": [10, "2CAG", "JT"],
    "PICKLE_BALL_G": [12, "2CAG", "JT"],
    "BADMINTON_B": [10, "MPH", "IQ"],
    "BADMINTON_G": [14, "MPH", "IQ"],
    "FIT_AND_FAB_G": [21, "GYM / DANCE STUDIO", "YY"],
    "FLOORBALL_B": [20, "ISH", "CL"],
    "TABLE_TENNIS_B": [8, "AMPHI", "JL"],
    "TABLE_TENNIS_G": [14, "AMPHI", "JL"],
    "CHOICE_COUNT": ["Choice 1", "Choice 2", "Choice 3", "Choice 4"],
}

thurs0825 = {
    "FLOORBALL_G": [26, "ISH", "SH"],
    "FOOTBALL_B": [24, "MAIN FIELD 1", "IQ"],
    "VOLLEYBALL_B": [13, "2CAG", "XX"],
    "VOLLEYBALL_G": [12, "2CAG", "XX"],
    "TENNIS_B": [8, "TC", "SY"],
    "TENNIS_G": [12, "TC", "SY"],
    "BASKETBALL_B": [26, "BBC", "BF"],
    "HANDBALL_G": [26, "GC", "JL"],
    "FRISBEE_G": [26, "MAIN FIELD 2", "YY"],
    "TABLE_TENNIS_B": [10, "AMPHI", "CJ"],
    "TABLE_TENNIS_G": [13, "AMPHI", "CJ"],
    "BADMINTON_B": [10, "MPH", "MY"],
    "BADMINTON_G": [14, "MPH", "MY"],
    "FRISBEE_B": [26, "HF", "GP"],
    "GROUP_EXERCISE_G": [17, "GYM / DANCE STUDIO", "CC"],
    "CHOICE_COUNT": [
        "Choice 1",
        "Choice 2",
        "Choice 3",
        "Choice 4",
        "Choice 5",
        "Choice 6",
        "Choice 7",
        "Choice 8",
    ],
}

thurs0920 = {
    "TOUCH_TAG_RUGBY_G": [24, "HF", "MO"],
    "TENNIS_B": [10, "TC", "VC"],
    "TENNIS_G": [10, "TC", "VC"],
    "FRISBEE_B": [22, "MAIN FIELD 1", "SK"],
    "VOLLEYBALL_B": [12, "2CAG", "CL"],
    "VOLLEYBALL_G": [12, "2CAG", "CL"],
    "FLOORBALL_G": [22, "ISH", "CC"],
    "BADMINTON_B": [10, "MPH", "MY"],
    "BADMINTON_G": [14, "MPH", "MY"],
    "TABLE_TENNIS_B": [10, "AMPHI", "DK"],
    "TABLE_TENNIS_G": [12, "AMPHI", "DK"],
    "PICKLE_BALL_B": [12, "BBC", "JT"],
    "PICKLE_BALL_G": [12, "BBC", "JT"],
    "HANDBALL_B": [16, "GC", "SH"],
    "CHOICE_COUNT": [
        "Choice 1",
        "Choice 2",
        "Choice 3",
        "Choice 4",
        "Choice 5",
        "Choice 6",
        "Choice 7",
    ],
}

fri0825 = {
    "FRISBEE_G": [26, "MAIN FIELD 3", "CC"],
    "BADMINTON_G": [24, "MPH", "CJ"],
    "BASKETBALL_G": [24, "BBC", "YY"],
    "STREET_NETBALL_G": [24, "STDM D", "RT"],
    "FOOTBALL_B": [22, "MAIN FIELD 1", "IQ"],
    "TOUCH_TAG_RUGBY_G": [26, "MAIN FIELD 2", "MO"],
    "FRISBEE_B": [24, "HF", "GP"],
    "FLOORBALL_B": [22, "ISH", "CL"],
    "TENNIS_B": [18, "TC", "SY"],
    "TABLE_TENNIS_B": [12, "AMPHI", "VC"],
    "TABLE_TENNIS_G": [10, "AMPHI", "VC"],
    "PICKLE_BALL_B": [8, "Parade Square", "JT"],
    "PICKLE_BALL_G": [15, "Parade Square", "JT"],
    "HANDBALL_B": [22, "GC", "SH"],
    "CHOICE_COUNT": [
        "Choice 1",
        "Choice 2",
        "Choice 3",
        "Choice 4",
        "Choice 5",
        "Choice 6",
        "Choice 7",
    ],
}

fri0920 = {
    "STREET_NETBALL_G": [20, "Stadium D", "DK"],
    "HANDBALL_G": [24, "BBC", "SH"],
    "TENNIS_B": [10, "TC", "BF"],
    "TENNIS_G": [10, "TC", "BF"],
    "FOOTBALL_B": [20, "Main Field 1", "XX"],
    "TOUCH_TAG_RUGBY_G": [24, "Main Field 2", "YY"],
    "HANDBALL_B": [18, "GC", "JL"],
    "BADMINTON_B": [11, "MPH", "MY"],
    "BADMINTON_G": [12, "MPH", "MY"],
    "LACROSSE_G": [23, "HF", "SK"],
    "CHOICE_COUNT": [
        "Choice 1",
        "Choice 2",
        "Choice 3",
        "Choice 4",
        "Choice 5",
        "Choice 6",
    ],
}

fri1015 = {
    "STREET_NETBALL_G": [22, "Stadium D", "RT"],
    "FRISBEE_B": [15, "Main Field 2", "CJ"],
    "FRISBEE_G": [11, "Main Field 2", "CJ"],
    "FOOTBALL_B": [26, "Main Field 1", "XX"],
    "TENNIS_B": [14, "TC", "IQ"],
    "TENNIS_G": [6, "TC", "IQ"],
    "HOCKEY_B": [20, "HF", "GP"],
    "GROUP_EXERCISE_G": [17, "GYM / DANCE STUDIO", "JT"],
    "CHOICE_COUNT": ["Choice 1", "Choice 2", "Choice 3", "Choice 4"],
}
